/* AndreuMatic VA extra (serveis, precios, legales, 404). Se fusiona en lang.js. */
window.AM_X1 = {
pg_index_t: 'Suport IT per a empreses a València | Auditoria, Iguala i Automatització – AndreuMatic',
pg_index_d: 'Suport IT i manteniment informàtic per a PIMEs a València: auditoria Nivell 3, iguala mensual i automatització amb IA. 654 225 831.',
pg_serv_t: 'Serveis IT per a empreses a València | Auditoria, Iguala i Automatització – AndreuMatic',
pg_serv_d: 'Serveis IT per a PIMEs a València: auditoria Nivell 3, iguala mensual, automatització amb IA i ciberseguretat. Pressupost tancat.',
pg_pre_t: 'Preus B2B: Auditoria, Iguala i Automatització | AndreuMatic',
pg_pre_d: 'Preus per a empreses a València: auditoria tecnològica des de 250€, iguala des de 35€/equip i 80€/servidor al mes, automatització amb pressupost a mida segons ROI. Pressupost tancat.',
pg_atc_t: 'Atenció al client | AndreuMatic',
pg_atc_d: 'Atenció al client d’AndreuMatic: canals, horari i compromís de resposta el mateix dia laborable.',
pg_av_t: 'Avís legal | AndreuMatic',
pg_av_d: 'Avís legal d’AndreuMatic: dades del titular, objecte de la web, propietat intel·lectual i responsabilitat.',
pg_pv_t: 'Política de privacitat | AndreuMatic',
pg_pv_d: 'Política de privacitat d’AndreuMatic: quines dades tractem, per a què, els teus drets i com exercir-los (RGPD i LOPDGDD).',
pg_ac_t: 'Declaració d’accessibilitat | AndreuMatic',
pg_ac_d: 'Declaració d’accessibilitat d’AndreuMatic: compromís, mesures aplicades i contacte davant barreres d’accés.',
pg_en_t: 'Entregues i reclamacions | AndreuMatic',
pg_en_d: 'Entregues i reclamacions a AndreuMatic: com prestem el servei, garantia de 15 dies i com reclamar.',
pg_404_t: 'Pàgina no trobada – AndreuMatic',
hdr_pres: 'Demanar pressupost',
back_home: '← Tornar a l’inici',
foot_val: 'València',
band_h2: 'Parlem de la teua empresa?',
band_p: 'Demanar la teua auditoria o conta’ns el teu cas. Contestem hui. Telefona al <a href="tel:+34654225831">654 225 831</a> o escriu a <a href="mailto:info@andreumatic.com">info@andreumatic.com</a>.',
sv_eb: 'Serveis per a empreses · què resolem',
sv_t: 'Tres solucions perquè el teu negoci no es pare.',
sv_lead: 'Des d’intervencions puntuals per a resoldre urgències fins a manteniment continu per a evitar parades en el teu negoci.',
sv_precios: 'Anar a preus →',
sv_part_t: 'Intervencions puntuals — quan necessites alguna cosa concreta',
sv_call: '<b>No saps quin servei és el teu?</b> No passa res. <a href="index.html#contacto">Conta’ns-ho amb les teues paraules</a> i ho classifiquem.',
sv_emp_t: 'Empreses i PIMEs — les teues 3 solucions core',
sv_emp_lead: 'El dolor ací són diners: un lloc parat, un servidor caigut, hores perdudes en tasques manuals. Manteniment informàtic amb resposta el mateix dia laborable.',
sv_a1: '<span class="tag">NIVELL 3</span><h3>1. Auditoria de rendiment i problemes complexos</h3><p>La teua xarxa o servidor va lent i altres tècnics no donen amb la causa.</p><p>Diagnòstic profund de xarxa, servidors i llocs: medim, trobem el coll de botella i t’entreguem informe amb solució i cost tancat.</p><p><a class="link-more" href="index.html?servicio=pc-lento#contacto">Demanar auditoria →</a> · <a class="link-more" href="precios.html#particulares">Vore preu</a></p>',
sv_a2: '<span class="tag">URGENT</span><h3>2. Recuperació de dades d’empresa</h3><p>“Hem perdut la carpeta de facturació”. Pànic total.</p><p>Discos, NAS, USB i còpies. Diagnòstic del fallo, intent de rescat i còpia segura. Si no es pot, t’ho diem clar des de l’inici.</p><p><a class="link-more" href="index.html?servicio=datos#contacto">Demanar este servei →</a></p>',
sv_a3: '<span class="tag">ZERO ESTRÉS</span><h3>3. Lloc nou llest el primer dia</h3><p>Donen d’alta a algú i el seu equip tarda dies a estar llest.</p><p>Migrem archius, correu, programes i accessos. Encén l’equip i tot està on ha d’estar.</p><p><a class="link-more" href="index.html?servicio=mudanza#contacto">Demanar este servei →</a></p>',
sv_a4: '<span class="tag">SENSE RISC</span><h3>4. Assessoria de compres per al teu equip</h3><p>Massa models i por de pagar de més o quedar-te curt.</p><p>Et diem què comprar segons l’ús real de la teua empresa i revisem pressupostos abans que pagues.</p><p><a class="link-more" href="index.html?servicio=compras#contacto">Demanar assessoria →</a></p>',
sv_a5: '<span class="tag">EL TEU SOCI IT</span><h3>5. El teu tècnic de referència</h3><p>Dubtes del dia a dia que llastren al teu equip.</p><p>PC, correu, impressora i programes, en remot o presencial. Com tindre un IT a casa, sense contractar-lo.</p><p><a class="link-more" href="index.html?servicio=cabecera#contacto">Demanar visita →</a></p>',
sv_a6: '<span class="tag">REMOT</span><h3>6. Suport en remot</h3><p>Si no cal desplaçar-nos, ens connectem i ho resolem en el moment. Ràpid i econòmic. Ideal per a urgències lleus.</p><p><a class="link-more" href="index.html?servicio=remoto#contacto">Demanar remot →</a></p>'
};
window.AM_X2 = {
sv_a7: '<span class="tag">TRANQUIL·LITAT</span><h3>7. Ciberseguretat i backups comprovats</h3><p>Contrasenyes, antivirus, anti-phishing i còpies que sí es verifiquen. Perquè un susto no pare el teu negoci.</p><p><a class="link-more" href="index.html?servicio=seguridad#contacto">Demanar revisió →</a></p>',
sv_a8: '<span class="tag">OFICINA</span><h3>8. Xarxa wifi i oficina connectada</h3><p>Router, punts d’accés, impressores en xarxa i càmeres. Internet que arriba a tota l’oficina i sense talls.</p><p><a class="link-more" href="index.html?servicio=hogar#contacto">Demanar ajuda wifi →</a></p>',
sv_a9: '<span class="tag">PREVENCIÓ</span><h3>9. Manteniment preventiu</h3><p>Revisió periòdica perquè els problemes no tornen. Detectem fallos abans que paren el teu negoci.</p><p><a class="link-more" href="precios.html#particulares">Vore preu diagnòstic</a></p>',
sv_a10: '<span class="tag">WEB</span><h3>10. Web i correu d’empresa</h3><p>Hosting, domini, correu corporatiu que no arriba, WordPress caigut. El teu aparador sempre obert.</p><p><a class="link-more" href="index.html?servicio=web#contacto">Demanar ajuda web →</a></p>',
sv_a11: '<span class="tag">A MIDA</span><h3>11. Automatització a mida amb IA</h3><p>Passeu hores amb Excels caòtics i tasques manuals? Creem aplicacions internes i automatitzacions: documents que s’omplin sols, avisos automàtics, dades que fluïxen sense copiar a mà. Pressupost tancat després de diagnòstic, sense compromís.</p><p><a class="link-more" href="index.html#contacto">Demanar diagnòstic →</a> · <a class="link-more" href="https://wa.me/34654225831?text=Hola%2C%20quiero%20una%20soluci%C3%B3n%20de%20software%20a%20medida">Preguntar per WhatsApp →</a></p>',
sv_a12: '<span class="tag">TOT CONNECTAT</span><h3>12. Integració de sistemes</h3><p>Facturació per un costat, correu per un altre, web desconnectada… Cada sistema solt et roba temps. Ho connectem tot perquè la informació fluïsca sola: menys clics, menys errors.</p><p><a class="link-more" href="index.html#contacto">Demanar diagnòstic →</a> · <a class="link-more" href="https://wa.me/34654225831?text=Hola%2C%20quiero%20integrar%20mis%20servicios">Preguntar per WhatsApp →</a></p>',
sv_e1: '<span class="tag">NIVELL 3</span><h3>Auditoria i urgències el mateix dia</h3><p>Problema complex o crític: diagnòstic profund fins donar amb la causa, amb informe clar i solució. Prioritat total per a la teua empresa.</p><p><a class="link-more" href="tel:+34654225831">Demanar urgència →</a></p>',
sv_e2: '<h3>Lloc nou llest el primer dia</h3><p>Ordinador, correu, programes, impressora i accessos configurats. El teu empleat produïx des del minut u.</p><p><a class="link-more" href="index.html?servicio=mudanza#contacto">Demanar lloc →</a></p>',
sv_e3: '<h3>Dades a salvo: backups supervisats</h3><p>Instal·lació + supervisió mensual que sí es comprova. Si passa alguna cosa, recuperem. Dormir tranquil també és rendibilitat.</p><p><a class="link-more" href="precios.html#empresas">Vore preu backups</a></p>',
sv_e4: '<h3>Iguala mensual: el teu IT extern</h3><p>Suport continu per lloc (remot o presencial) + prioritat el mateix dia laborable. Sense contractar personal.</p><p><a class="link-more" href="precios.html#empresas">Vore què és la iguala</a></p>',
sv_e5: '<h3>Assessorament integral + configuracions</h3><p>Què comprar, què renovar, quin software val la pena. Decisions amb criteri, no per impuls comercial.</p><p><a class="link-more" href="index.html?servicio=compras#contacto">Demanar assessoria →</a></p>',
sv_e6: '<h3>Web i correu empresa</h3><p>Caigudes, dominis, hosting, WordPress. El teu aparador sempre obert.</p><p><a class="link-more" href="index.html?servicio=web#contacto">Demanar ajuda →</a></p>',
sv_e7: '<span class="tag">A MIDA</span><h3>Automatització amb IA a mida</h3><p>Eixe procés que feu a mà, eixes dades que copieu d’un lloc a un altre… Ho automatitzem: menys hores perdudes, menys errors humans. Pressupost tancat després de diagnòstic.</p><p><a class="link-more" href="index.html#contacto">Demanar diagnòstic →</a></p>',
sv_e8: '<span class="tag">TOT CONNECTAT</span><h3>Integració de sistemes</h3><p>Facturació, correu, còpies, web, CRM… Si cada sistema va per lliure, el negoci perd ritme. Els integrem perquè la informació fluïsca sola.</p><p><a class="link-more" href="index.html#contacto">Demanar diagnòstic →</a></p>',
sv_band_h: 'Parlem de la teua empresa?',
sv_band_p: 'Demanar la teua auditoria o conta’ns el teu cas. Contestem hui. Telefona al <a href="tel:+34654225831">654 225 831</a> o escriu a <a href="mailto:info@andreumatic.com">info@andreumatic.com</a>.',
sv_band_pre: 'Vore preus'
};
window.AM_X3 = {
pr_eb: 'Preus B2B · clars i sense lletra menuda',
pr_t: 'Sabràs lo que pagues abans de començar.',
pr_lead: 'Sense lletra menuda. Tria el teu servei en <a class="link-more" href="servicios.html">Serveis</a>, consulta ací la referència de manteniment informàtic i escriu-nos per a tancar la teua auditoria o la teua iguala. Tot amb pressupost tancat.',
pr_part_t: 'Solucions Estratègiques per a PIMEs',
pr_r1: 'Auditoria Tecnològica i de Rendiment<small>Diagnòstic de xarxa, seguretat i hardware + informe executiu</small>',
pr_r2: 'Manteniment Preventiu i Suport Nivell 3<small>Des de 35€/equip i 80€/servidor al mes</small>',
pr_r3: 'Iguala per servidor: monitorització 24/7<small>Servidors sempre vigilats</small>',
pr_r4: 'Automatització de Processos amb IA<small>Adéu Excels caòtics i tasques manuals</small>',
pr_r5: 'Desenvolupament Web a Mida B2B<small>Webs orientades a negoci i conversió</small>',
pr_r6: 'Posicionament SEO Tècnic<small>Auditoria SEO i optimització per a captar clients</small>',
pr_r7: 'Redisseny per a Captació<small>Transformem la teua web en una ferramenta de vendes</small>',
pr_incl: '— Inclòs en totes les nostres igualas de manteniment —',
pr_r8: 'Informe executiu + pla d’acció<small>Prioritzat per impacte en el teu negoci</small>',
pr_r9: 'Monitorització contínua<small>Detectem fallos abans que paren el teu negoci</small>',
pr_r10: 'Backups immutables verificats<small>Còpies que sí es comproven i es recuperen</small>',
pr_r11: 'SLA garantit<small>Resposta el mateix dia laborable</small>',
pr_r12: 'Revisió de llocs i accessos<small>Equips, programes i permisos per empleat</small>',
pr_call1: '<b>Urgències:</b> prioritat el mateix dia laborable per a empreses amb iguala.',
pr_call2: '<b>Garantia 15 dies</b> en el treball realitzat. I pressupost tancat abans de començar, sempre.',
pr_cta_part: 'Demanar la meua auditoria →',
pr_emp_t: 'Intervencions Puntuals',
pr_top_t: 'Solucions Estratègiques per a PIMEs',
pr_bot_t: 'Intervencions Puntuals',
pr_e1: 'Urgències en el dia<small>Prioritat total, mateix dia laborable</small>',
pr_e3: 'Diagnòstic puntual amb informe<small>Causa, cost i termini per escrit</small>',
pr_e4: 'Lloc nou llest el primer dia<small>Equip, correu i accessos</small>',
pr_e5: 'Recuperació de dades<small>Discos, NAS i còpies</small>',
pr_e6: 'Revisió de seguretat puntual<small>Accessos, antivirus i 2FA</small>',
pr_e7: 'Web i correu: resolució puntual<small>Caigudes, hosting, correu corporatiu</small>',
pr_e8: 'Assessoria de compra puntual<small>Què renovar i què evitar</small>',
pr_e9: 'Xarxa wifi d’oficina puntual<small>Cobertura i impressores en xarxa</small>',
pr_e10: 'Integració puntual entre sistemes<small>Dos programes que per fi parlen</small>',
pr_call3: '<b>Necessites continuïtat?</b> Les intervencions resolen lo urgent. La iguala ho evita: monitorització + remot prioritari + còpies + SLA.',
pr_call4: '<b>Remot immediat i visites a la teua empresa</b> — tu no et mous.',
pr_cta_emp: 'Demanar pressupost empresa →',
pr_not_t: 'Notes sobre preus',
pr_call5: '<b>🚗 Visites a la teua empresa des de 15€:</b> a València ciutat i rodalia (Paterna, Torrent, Mislata, Burjassot, Quart de Poblet, Aldaia, Manises, Paiporta, Alboraia, Xirivella i Alaquàs). Es confirma l’import exacte abans d’eixir. En remot no hi ha desplaçament.',
pr_call6: '<b>Què significa “des de”?</b> És la referència mínima segons núm. d’equips o abast. Sempre et donem <b>pressupost tancat abans</b> i només seguixes si t’encaixa.',
pr_call7: '<b>🛡️ Si no té arregle, no pagues de més:</b> t’ho diem clar des de l’informe. Et proposem l’alternativa amb millor cost per al teu negoci.',
pr_call8: '<b>** Tarifes no especificades:</b> pot haver-hi tarifes no especificades que es definiran segons la urgència, magnitud i resolució del problema.',
pr_notfoot: '*** Les tarifes poden patir canvis per demanda, disponibilitat, tipus de resolució o canvis de mercat.',
pr_band_h: 'Quin servei necessita la teua empresa?',
pr_band_back: '← Tornar a serveis',
};
window.AM_X4 = {
pr_e2: 'Suport en remot<small>Ens connectem i ho resolem en el moment</small>',
atc_lead: 'Parles amb qui ho resol: el teu soci tecnològic, sense call centers ni 902.',
atc_h1: '1. Canals',
atc_p1: 'Telèfon i WhatsApp: <a class="link-more" href="tel:+34654225831">654 225 831</a> · Email: <a class="link-more" href="mailto:info@andreumatic.com">info@andreumatic.com</a>',
atc_h2: '2. Horari',
atc_p2: 'Dilluns a divendres, de 9:00 a 19:00. Fora d’horari pots escriure’ns i et responem al següent dia laborable.',
atc_h3: '3. Compromís de resposta',
atc_p3: 'Contestem el mateix dia laborable. Les urgències tenen prioritat amb el servei del mateix dia.',
atc_h4: '4. Zona de servei',
atc_p4: 'València i rodalia, a la teua oficina. Fora de zona? Gran part es resol en remot.',
av_lead: 'Qui som i baix quines regles funciona esta web.',
av_h1: '1. Dades del titular',
av_p1: 'Titular: Andreu Zaragozà i Arnàez · NIF: 48588243F<br>Domicili: Calle Mare Nostrum 6-4, 46930 Quart de Poblet (Valencia)<br>Contacte: <a class="link-more" href="tel:+34654225831">654 225 831</a> · <a class="link-more" href="mailto:info@andreumatic.com">info@andreumatic.com</a>',
av_h2: '2. Objecte de la web',
av_p2: 'Esta web informa dels nostres serveis i preus, i oferix canals de contacte. No permet contractar ni pagar online: tot servei es confirma directament amb el client per telèfon, email o WhatsApp.',
av_h3: '3. Preus',
av_p3: 'Els preus publicats són orientatius. El preu final es confirma amb el client abans de començar cada treball, després del diagnòstic. Cap extra s’aplica sense la seua aprovació prèvia. Vore <a class="link-more" href="precios.html#notas">notes sobre preus</a>.',
av_h4: '4. Propietat intel·lectual',
av_p4: 'Textos, imatges, logos i disseny d’esta web són titularitat d’AndreuMatic. No està permesa la seua reproducció sense autorització.',
av_h5: '5. Responsabilitat',
av_p5: 'Treballem perquè la informació estiga actualitzada, però no garantim la disponibilitat ininterrompuda de la web ni que estiga lliure d’errors. Els enllaços externs (p. ex. WhatsApp) es regixen per les condicions dels seus titulars.',
av_h6: '6. Llei aplicable',
av_p6: 'Legislació espanyola. Per a qualsevol conflicte seran competents els jutjats i tribunals de València, excepte norma imperativa en contra.',
pv_h1: 'Política de privacitat',
pv_lead: 'Clar i sense lletra menuda, com tot lo nostre.',
pv_r1: '1. Responsable',
pv_p1: 'Andreu Zaragozà i Arnàez (AndreuMatic) · NIF 48588243F · <a class="link-more" href="mailto:info@andreumatic.com">info@andreumatic.com</a> · <a class="link-more" href="tel:+34654225831">654 225 831</a>',
pv_r2: '2. Quines dades tractem',
pv_p2: 'Només les que tu ens facilites en contactar (formulari, email, telèfon o WhatsApp): nom, telèfon, email i la descripció del teu problema. Esta web no té comptes ni analítica. El formulari usa la verificació anti-spam Cloudflare Turnstile, que no utilitza cookies de seguiment.',
pv_r3: '3. Per a què i per què',
pv_p3: 'Per a respondre a les teues consultes i prestar-te el servei que contractes. Legitimació: el teu consentiment en escriure’ns i l’execució del servei (art. 6.1.a i 6.1.b del RGPD).',
pv_r4: '4. Quant de temps',
pv_p4: 'Només el necessari per a atendre’t i complir obligacions legals (p. ex. facturació). Després, s’eliminen.',
pv_r5: '5. Destinataris',
pv_p5: 'No cedim dades a tercers, excepte obligació legal. Si ens escrius per WhatsApp, tingues en compte que Meta processa eixos missatges segons la seua pròpia política de privacitat.',
pv_r6: '6. Els teus drets',
pv_p6: 'Accés, rectificació, supressió, oposició, limitació i portabilitat: escriu-nos a <a class="link-more" href="mailto:info@andreumatic.com">info@andreumatic.com</a> i ho resolem. També pots reclamar davant l’Agència Espanyola de Protecció de Dades (aepd.es).',
ac_h1: 'Declaració d’accessibilitat',
ac_lead: 'Esta web és per a tots. Si alguna cosa t’ho posa difícil, digue’ns-ho i ho arreglem.',
ac_r1: '1. Compromís',
ac_p1: 'AndreuMatic es compromet que esta web siga accessible conforme a la Llei 11/2023 de transposició de la Directiva (UE) 2019/882, amb l’objectiu de complir el nivell AA de les WCAG 2.1.',
ac_r2: '2. Mesures aplicades',
ac_p2: 'Textos alternatius en imatges, contrast reforçat, navegació completa per teclat, disseny responsive per a mòbil i llenguatge clar sense tecnicismes.',
ac_r3: '3. Limitacions',
ac_p3: 'Alguns continguts de tercers (p. ex. mapes o chats externs) poden no complir plenament estos criteris. Treballem a revisar-los i oferir alternatives.',
ac_r4: '4. Contacte davant barreres',
ac_p4: 'Si trobes alguna barrera d’accés, escriu-nos a <a class="link-more" href="mailto:info@andreumatic.com">info@andreumatic.com</a> o telefona al <a class="link-more" href="tel:+34654225831">654 225 831</a>. Responem en un màxim de 15 dies laborables.',
ac_rev: 'Última revisió: setembre de 2026.',
en_lead: 'Ací no hi ha enviaments: hi ha servei presencial a la teua empresa, remot i arreplegada. Açò és lo que pots esperar.',
en_h1: '1. Com es presta el servei',
en_p1: 'Presencial a la teua empresa a València i rodalia, en remot, o amb arreplegada i entrega d’equips en taller. No realitzem enviaments de productes: el nostre treball és el servei tècnic per a empreses.',
en_h2: '2. Terminis',
en_p2: 'Els terminis són orientatius i es confirmen en contractar cada servei. Les urgències s’atenen el mateix dia laborable segons disponibilitat.',
en_h3: '3. Garantia',
en_p3: '15 dies en el treball realitzat. No cobrix fallos de programes de tercers ni mal ús posterior.',
en_h4: '4. Com reclamar',
en_p4: 'Telefona’ns al <a class="link-more" href="tel:+34654225831">654 225 831</a>, escriu-nos a <a class="link-more" href="mailto:info@andreumatic.com">info@andreumatic.com</a> o per <a class="link-more" href="https://wa.me/34654225831?text=Hola%20AndreuMatic%2C%20quiero%20poner%20una%20reclamación">WhatsApp</a>. També tens a la teua disposició els fulls de reclamacions de la Generalitat Valenciana i la plataforma europea de resolució de litigis en línia: <a class="link-more" href="https://ec.europa.eu/consumers/odr">ec.europa.eu/consumers/odr</a>.',
fof_h1: 'Vaja, açò s’ha trencat… però jo ho arregle.',
fof_p: 'La pàgina no existix. Millor parlem directament.'
};
window.AM_X5 = {
pg_cita_t: 'Agenda la teua telefonada de diagnòstic | AndreuMatic',
pg_cita_d: 'Agenda la teua telefonada de diagnòstic de 15 minuts amb AndreuMatic: entenem el teu negoci i et proposem un pla d’acció. O demanar la teua Auditoria Tecnològica.',
ci_crumb: 'Agenda la teua telefonada',
ci_eb: 'Telefonada de diagnòstic · 15 minuts',
ci_t: 'Agenda la teua telefonada o demanar la teua auditoria',
ci_lead: 'Tria dia i hora dels espais disponibles. Tindrem una breu reunió per telèfon o videotelefonada per a entendre el teu negoci i proposar-te un pla d’acció. Sense compromís.',
ci_s1t: '1. Tria dia i hora',
ci_s1p: 'Calendari amb disponibilitat real, actualitzat al moment.',
ci_s2t: '2. Conta’ns el teu negoci',
ci_s2p: 'Què et preocupa: lentitud, còpies, tasques manuals. Només lo necessari.',
ci_s3t: '3. Rep el teu pla d’acció',
ci_s3p: 'Diagnòstic clar + proposta amb cost tancat. Tu decidixes.',
ci_alt: 'Prefirixes escriure? <a class="link-more" href="index.html#contacto">Ves al formulari →</a> o <a class="link-more" href="https://wa.me/34654225831?text=Hola%20AndreuMatic%2C%20quiero%20pedir%20cita">WhatsApp directe</a>.'
};
window.AM_X6 = {
sl_t: 'Disponibilitat esta setmana'
};
window.AM_X7 = {
pr_iva: 'Preus sense IVA (Base Imposable). L’automatització a mida es pressuposta segons ROI.',
pv_p6: 'Accés, rectificació, supressió, oposició, limitació i portabilitat: escriu-nos a <a class="link-more" href="mailto:info@andreumatic.com">info@andreumatic.com</a> i ho resolem en el termini màxim d’un mes. També pots reclamar davant l’Agència Espanyola de Protecció de Dades (aepd.es).',
pv_r7: '7. Encarregats del tractament',
pv_p7: 'Per a prestar-te el servei usem: <b>Resend</b> (enviament dels emails de contacte) i <b>Cloudflare</b> (seguretat i anti-spam de la web). Només tracten les teues dades per a això i baix les nostres instruccions.',
pv_r8: '8. Emmagatzematge local (sense cookies)',
pv_p8: 'Esta web no usa cookies de seguiment ni analítica. Només guarda en el teu propi navegador l’idioma triat i una memòria cau temporal de disponibilitat (10 minuts). Les tipografies es serveixen des del nostre propi domini, sense connexions a tercers. Pots esborrar-los quan vullgues des del teu navegador.',
en_h5: '5. Dret de desistiment',
en_p5: 'En contractar fora d’establiment (a la teua empresa u oficina) tens 14 dies naturals per a desistir sense justificar. No s’aplica si el servei ja s’ha prestat per complet amb el teu consentiment o si vas demanar una intervenció urgent immediata. Per a exercir-lo, escriu-nos a <a class="link-more" href="mailto:info@andreumatic.com">info@andreumatic.com</a>.'
};
window.AM_X8 = {
hdr_cita: 'Agenda la teua telefonada',
oz: 'Altres zones:',
mn_pre: 'Vore preus clars →',
mn_serv: 'Vore tots els serveis →',
pg_mn_t: 'Suport Informàtic per a Empreses a Manises | Manteniment i Xarxes – AndreuMatic',
pg_mn_d: 'Auditoria IT, manteniment de servidors, còpies de seguretat i automatització per a PIMEs a Manises. Suport presencial ràpid.',
mn_crumb: 'Suport IT empreses a Manises',
mn_eb: 'Manises · a un pas de la teua empresa',
mn_t: 'El teu soci tecnològic a Manises',
mn_lead: 'Suport IT i manteniment informàtic perquè la teua empresa no es detinga. Estem a un pas de la teua oficina i del polígon industrial a Manises: resposta el mateix dia laborable, sense tecnicismes.',
mn_b1: 'Manteniment de flotes d’equips i llocs llests dia 1',
mn_b2: 'Servidors i xarxes: auditoria i colls de botella resolts',
mn_b3: 'Backups immutables supervisats + automatització amb IA',
mn_b4: 'Desenvolupament web i SEO B2B per a captar clients',
mn_p2: 'Treballem en tot Manises — centre, Barri Nou, Socusa, polígon i voltants de l’aeroport — amb visites presencials i remot immediat. Auditoria amb informe des de 250€.',
pg_qt_t: 'Suport Informàtic per a Empreses a Quart de Poblet | Manteniment i Xarxes – AndreuMatic',
pg_qt_d: 'Auditoria IT, manteniment de servidors, còpies de seguretat i automatització per a PIMEs a Quart de Poblet. Estem al teu poble: suport presencial rapidíssim.',
qt_crumb: 'Suport IT empreses a Quart de Poblet',
qt_eb: 'Quart de Poblet · el teu soci tecnològic veí',
qt_t: 'El teu soci tecnològic a Quart de Poblet',
qt_lead: 'Suport IT i manteniment informàtic perquè la teua empresa no es detinga. Estem al teu mateix poble, així que la resposta és immediata: hui mateix o demà a primera hora, amb pressupost tancat abans de començar.',
qt_b1: 'Resposta el mateix dia en tot Quart: centre, Riu Túria i polígons',
qt_b2: 'Servidors, xarxes i flotes d’equips sempre a punt',
qt_b3: 'Backups immutables + remot immediat per a urgències',
qt_b4: 'Automatització amb IA, web i SEO per a captar clients',
qt_p2: 'En estar ací, el desplaçament és mínim i molt ho resolem en remot en el moment. Auditoria amb informe des de 250€.'
};
window.AM_X9 = {
pg_vl_t: 'Suport Informàtic per a Empreses a València | Manteniment i Xarxes – AndreuMatic',
pg_vl_d: 'Auditoria IT, manteniment de servidors, còpies de seguretat i automatització per a PIMEs a València. Suport presencial ràpid.',
vl_crumb: 'Suport IT empreses a València',
vl_eb: 'València capital · el teu soci tecnològic',
vl_t: 'El teu soci tecnològic a València',
vl_lead: 'Suport IT i manteniment informàtic perquè la teua empresa no es detinga. Del Carme a Russafa, de Patraix a Benimaclet: estem a un pas de la teua oficina a València capital, amb resposta el mateix dia laborable.',
vl_b1: 'Auditoria IT i xarxes: trobem lo que altres no resolen',
vl_b2: 'Iguala mensual: flotes d’equips, servidors i backups immutables',
vl_b3: 'Automatització amb IA i web/SEO B2B per a captar clients',
vl_b4: 'Pressupost tancat abans de començar i SLA garantit',
vl_p2: 'Base a Quart de Poblet, a 10 minuts de València: visites a la teua oficina amb desplaçament mínim i auditoria amb informe des de 250€.',
pg_mi_t: 'Suport Informàtic per a Empreses a Mislata | Manteniment i Xarxes – AndreuMatic',
pg_mi_d: 'Auditoria IT, manteniment de servidors, còpies de seguretat i automatització per a PIMEs a Mislata. Suport presencial ràpid.',
mi_crumb: 'Suport IT empreses a Mislata',
mi_eb: 'Mislata · a 5 minuts de la teua empresa',
mi_t: 'El teu soci tecnològic a Mislata',
mi_lead: 'Suport IT i manteniment informàtic perquè la teua empresa no es detinga. Estem a un pas de la teua oficina a Mislata: creuem en minuts i ho deixem funcionant amb pressupost tancat.',
mi_b1: 'Visita ràpida en tota Mislata: centre, La Creu i voltants',
mi_b2: 'Flotes d’equips i llocs llests el primer dia',
mi_b3: 'Servidors, xarxes i backups immutables supervisats',
mi_b4: 'Automatització amb IA + web i SEO per a captar clients',
mi_p2: 'En estar al costat, el desplaçament és mínim: auditoria amb informe des de 250€ i urgències el mateix dia laborable.'
};
window.AM_X10 = {
mn_em_t: 'Empreses i PIMEs a Manises',
mn_em_p: 'El teu tècnic informàtic a Manises: urgències el mateix dia laborable per a oficines i naus del polígon, iguala mensual i còpies a salvo. Sense parar la teua activitat.',
mn_f1q: 'Veniu a la nostra oficina a Manises?',
mn_f1a: 'Sí: som la teua empresa informàtica a Manises — centre, Barri Nou, Socusa, polígon i aeroport. El desplaçament és mínim.',
mn_f2q: 'Quant costa l’auditoria?',
mn_f2a: 'Des de 250€ amb informe executiu. Preu tancat abans de començar.',
mn_f3q: 'I si és urgent?',
mn_f3a: 'Mateix dia laborable per a empreses. Escriu-nos i et diem hora real.',
qt_em_t: 'Empreses i PIMEs a Quart de Poblet',
qt_em_p: 'El teu tècnic informàtic a Quart: estant al poble, les teues urgències són les primeres de la llista — mateix dia laborable, llocs nous i iguala mensual.',
qt_f1q: 'Esteu a Quart de veritat?',
qt_f1a: 'Sí, som la teua empresa informàtica a Quart, amb base ací: resposta hui mateix o demà a primera hora en tot el poble i polígons.',
qt_f2q: 'Feu iguala mensual?',
qt_f2a: 'Sí: monitorització, remot prioritari, còpies i SLA. El teu IT extern.',
qt_f3q: 'Quant costa l’auditoria?',
qt_f3a: 'Des de 250€ amb informe executiu. Preu tancat abans de començar.',
vl_em_t: 'Empreses i PIMEs a València capital',
vl_em_p: 'El teu tècnic informàtic a València: urgències el mateix dia laborable per a oficines, clíniques, assessories i naus de tots els barris, llocs llests el primer dia i còpies supervisades.',
vl_f1q: 'Arribeu a tota València?',
vl_f1a: 'Sí: del Carme a Russafa, de Patraix a Benimaclet, a la teua oficina.',
vl_f2q: 'Treballeu amb empreses?',
vl_f2a: 'Al 100%: som la teua empresa informàtica a València — auditoria, iguala mensual, automatització i web/SEO per a PIMEs.',
vl_f3q: 'Quant costa l’auditoria?',
vl_f3a: 'Des de 250€ amb informe executiu i pla d’acció. Preu tancat.',
mi_em_t: 'Empreses i PIMEs a Mislata',
mi_em_p: 'El teu tècnic informàtic a Mislata: que cap equip pare el teu dia. Urgències, iguala mensual i automatització per a negocis i autònoms.',
mi_f1q: 'Veniu a la nostra oficina a Mislata?',
mi_f1a: 'Sí: som la teua empresa informàtica a Mislata — centre, La Creu i voltants, amb desplaçament mínim.',
mi_f2q: 'Reviseu diversos equips en una visita?',
mi_f2a: 'Sí: auditem tota la teua flota — equips, xarxa i còpies — en una visita.',
mi_f3q: 'Quant costa l’auditoria?',
mi_f3a: 'Des de 250€ amb informe executiu. Preu tancat abans de començar.'
};
window.AM_X11 = {
mn_em_t: 'Empreses i PIMEs a Manises',
mn_em_p: 'El teu tècnic informàtic a Manises: urgències el mateix dia laborable per a oficines i naus del polígon, iguala mensual i còpies a salvo. Sense parar la teua activitat.',
mn_faq: 'Dubtes d’empreses a Manises',
mn_f1q: 'Veniu a la nostra oficina a Manises?',
mn_f1a: 'Sí: som la teua empresa informàtica a Manises — centre, Barri Nou, Socusa, polígon i aeroport. El desplaçament és mínim.',
mn_f2q: 'Quant costa l’auditoria?',
mn_f2a: 'Des de 250€ amb informe executiu. Preu tancat abans de començar.',
mn_f3q: 'I si és urgent?',
mn_f3a: 'Mateix dia laborable per a empreses. Escriu-nos i et diem hora real.',
qt_em_t: 'Empreses i PIMEs a Quart de Poblet',
qt_em_p: 'El teu tècnic informàtic a Quart: estant al poble, les teues urgències són les primeres de la llista — mateix dia laborable, llocs nous i iguala mensual.',
qt_faq: 'Dubtes d’empreses a Quart de Poblet',
qt_f1q: 'Esteu a Quart de veritat?',
qt_f1a: 'Sí, som la teua empresa informàtica a Quart, amb base ací: resposta hui mateix o demà a primera hora en tot el poble i polígons.',
qt_f2q: 'Feu iguala mensual?',
qt_f2a: 'Sí: monitorització, remot prioritari, còpies i SLA. El teu IT extern.',
qt_f3q: 'Quant costa l’auditoria?',
qt_f3a: 'Des de 250€ amb informe executiu. Preu tancat abans de començar.',
vl_em_t: 'Empreses i PIMEs a València capital',
vl_em_p: 'El teu tècnic informàtic a València: urgències el mateix dia laborable per a oficines, clíniques, assessories i naus de tots els barris, llocs llests el primer dia i còpies supervisades.',
vl_faq: 'Dubtes d’empreses a València',
vl_f1q: 'Arribeu a tota València?',
vl_f1a: 'Sí: del Carme a Russafa, de Patraix a Benimaclet, a la teua oficina.',
vl_f2q: 'Treballeu amb empreses?',
vl_f2a: 'Al 100%: som la teua empresa informàtica a València — auditoria, iguala mensual, automatització i web/SEO per a PIMEs.',
vl_f3q: 'Quant costa l’auditoria?',
vl_f3a: 'Des de 250€ amb informe executiu i pla d’acció. Preu tancat.',
mi_em_t: 'Empreses i PIMEs a Mislata',
mi_em_p: 'El teu tècnic informàtic a Mislata: que cap equip pare el teu dia. Urgències, iguala mensual i automatització per a negocis i autònoms.',
mi_faq: 'Dubtes d’empreses a Mislata',
mi_f1q: 'Veniu a la nostra oficina a Mislata?',
mi_f1a: 'Sí: som la teua empresa informàtica a Mislata — centre, La Creu i voltants, amb desplaçament mínim.',
mi_f2q: 'Reviseu diversos equips en una visita?',
mi_f2a: 'Sí: auditem tota la teua flota — equips, xarxa i còpies — en una visita.',
mi_f3q: 'Quant costa l’auditoria?',
mi_f3a: 'Des de 250€ amb informe executiu. Preu tancat abans de començar.'
};
