/* AndreuMatic VA extra (servicios, precios, legales, 404). Se fusiona en lang.js. */
window.AM_X1 = {
pg_index_t: 'Problemes amb la informàtica? Tècnic informàtic a València | AndreuMatic',
pg_index_d: 'Problemes amb la informàtica o la tecnologia? Servicis d’informàtica a València i rodalia: tècnic informàtic a domicili, +10 anys d’experiència. Sense sorpreses i amb garantia. WhatsApp: 654 225 831.',
pg_serv_t: 'Servicis informàtics València | Particulars i Empreses – AndreuMatic',
pg_serv_d: 'Tots els servicis AndreuMatic a València: PC lent, recuperació de dades, mudança a equip nou, assessoria de compres, seguretat, smart home, suport remot, tècnic de capçalera i servicis per a empreses.',
pg_pre_t: 'Preus clars tècnic informàtic València | AndreuMatic',
pg_pre_d: 'Preus clars a València: diagnòstic des de 25€, optimització PC des de 45€, recuperació dades des de 60€, remot 35€/h, empreses des de 25€. Mateix dia +15€. Garantia 15 dies. Sense sorpreses.',
pg_atc_t: 'Atenció al client | AndreuMatic',
pg_atc_d: 'Atenció al client d’AndreuMatic: canals, horari i compromís de resposta el mateix dia laborable.',
pg_av_t: 'Avís legal | AndreuMatic',
pg_av_d: 'Avís legal d’AndreuMatic: dades del titular, objecte de la web, propietat intel·lectual i responsabilitat.',
pg_pv_t: 'Política de privacitat | AndreuMatic',
pg_pv_d: 'Política de privacitat d’AndreuMatic: quines dades tractem, per a què, els teus drets i com exercir-los (RGPD i LOPDGDD).',
pg_ac_t: 'Declaració d’accessibilitat | AndreuMatic',
pg_ac_d: 'Declaració d’accessibilitat d’AndreuMatic: compromís, mesures aplicades i contacte davant barreres d’accés.',
pg_en_t: 'Entregues i reclamacions | AndreuMatic',
pg_en_d: 'Entregues i reclamacions a AndreuMatic: com prestem el servici, garantia de 15 dies i com reclamar.',
pg_404_t: 'Pàgina no trobada – AndreuMatic',
hdr_pres: 'Demanar pressupost',
back_home: '← Tornar a l’inici',
foot_val: 'València',
band_h2: 'Parlem del teu cas?',
band_p: 'Conta’ns què et passa i et contactem com més prompte millor.',
sv_eb: 'Servicis · què resolem (sense preus ací)',
sv_t: 'Tot lo que et fa mal de cap digital, resolt.',
sv_lead: 'Llig amb calma. Cada servici resol problemes concrets. I si no ho tens clar, <a class="link-more" href="https://wa.me/34654225831?text=Hola%20AndreuMatic%2C%20no%20tengo%20claro%20qué%20necesito">pregunta sense compromís</a> — et diem què necessites.',
sv_precios: 'Anar a preus →',
sv_part_t: 'Particulars — a casa, en remot o amb arreplegada',
sv_call: '<b>No saps quin servici és el teu?</b> No passa res. <a href="https://wa.me/34654225831?text=Hola%2C%20no%20s%C3%A9%20qu%C3%A9%20me%20pasa%20exactamente">Conta’ns-ho amb les teues paraules</a> i ho classifiquem.',
sv_emp_t: 'Empreses i autònoms — que res pare el teu negoci',
sv_emp_lead: 'El dolor ací són diners: un lloc parat, un correu caigut, un backup que no existix. Responem el mateix dia laborable.',
sv_a1: '<span class="tag">EL MÉS DEMANAT</span><h3>1. PC lent → ràpid (Optimització)</h3><p>Cada clic és etern, arranca en 10 min, tot es penja.</p><p>Inclou: neteja interna/externa, arranc, virus, programes que llastren, posada a punt. Te’l tornem optimitzat i llest per a volar!</p><p><a class="link-more" href="https://wa.me/34654225831?text=Hola%2C%20mi%20PC%20va%20lento%2C%20quiero%20optimizarlo">Demanar este servici →</a> · <a class="link-more" href="precios.html#particulares">Vore preu</a></p>',
sv_a2: '<span class="tag">URGENT</span><h3>2. Recuperació de dades i fotos</h3><p>“He perdut anys de fotos / treball”. Pànic total.</p><p>Discos, USB, targetes, mòbils. Diagnòstic del fallo, intent de rescat i còpia segura. Si no es pot, t’ho diem clar des de l’inici.</p><p><a class="link-more" href="https://wa.me/34654225831?text=Hola%2C%20necesito%20recuperar%20datos">Demanar este servici →</a></p>',
sv_a3: '<span class="tag">ZERO ESTRÉS</span><h3>3. Mudança a equip nou</h3><p>Estrenes PC i tems perdre programes, correu, contrasenyes.</p><p>Migrem archius, programes, configuració, correu i navegadors. Encens el nou i tot està on estava.</p><p><a class="link-more" href="https://wa.me/34654225831?text=Hola%2C%20quiero%20pasar%20todo%20a%20mi%20nuevo%20equipo">Demanar este servici →</a></p>',
sv_a4: '<span class="tag">ESTALVIA 600€</span><h3>4. Assessoria de compres + PC a mida</h3><p>200 models iguals, por que et colen lo car o lo roín.</p><p>Et diem què comprar segons el teu ús real, revisem enllaços abans que pagues. I si vols torre, la muntem i instal·lem (components a banda).</p><p><a class="link-more" href="https://wa.me/34654225831?text=Hola%2C%20quiero%20asesoramiento%20antes%20de%20comprar">Demanar assessoria →</a></p>',
sv_a5: '<span class="tag">EL TEU FAVORIT</span><h3>5. El Teu Tècnic de Capçalera</h3><p>Dubtes del dia a dia que ningú t’explica sense presses.</p><p>PC, mòbil, apps, correu, impressora… per visita o en remot. Com anar al metge de família, però digital.</p><p><a class="link-more" href="https://wa.me/34654225831?text=Hola%2C%20quiero%20mi%20t%C3%A9cnico%20de%20cabecera">Demanar visita →</a></p>',
sv_a6: '<span class="tag">REMOT</span><h3>6. Suport en remot</h3><p>Si no cal desplaçar-nos, ens connectem i ho resolem en el moment. Ràpid i econòmic. Ideal per a urgències lleus.</p><p><a class="link-more" href="https://wa.me/34654225831?text=Hola%2C%20necesito%20ayuda%20en%20remoto">Demanar remot →</a></p>'
};
window.AM_X2 = {
sv_a7: '<span class="tag">TRANQUIL·LITAT</span><h3>7. Revisió de seguretat digital</h3><p>Contrasenyes, còpies automàtiques, antivirus, anti-phishing. Perquè no et roben el compte ni els records.</p><p><a class="link-more" href="https://wa.me/34654225831?text=Hola%2C%20quiero%20revisi%C3%B3n%20de%20seguridad">Demanar revisió →</a></p>',
sv_a8: '<span class="tag">LLAR</span><h3>8. Smart home bàsic + wifi que funciona</h3><p>Router, repetidors, càmeres, endolls intel·ligents. Internet que arriba a tota la casa i sense talls.</p><p><a class="link-more" href="https://wa.me/34654225831?text=Hola%2C%20mi%20wifi%20-%20casa%20no%20va%20bien">Demanar ajuda wifi →</a></p>',
sv_a9: '<span class="tag">PREVENCIÓ</span><h3>9. Manteniment preventiu + visita diagnòstic</h3><p>Revisió anual perquè no torne el caos. La primera visita diagnòstica a casa, si repares, et ix gratis.</p><p><a class="link-more" href="precios.html#particulares">Vore preu diagnòstic</a></p>',
sv_a10: '<span class="tag">WEB</span><h3>10. Canvis i resolució de problemes en web</h3><p>Hosting, domini, correu que no arriba, WordPress trencat, textos i imatges. Per a particulars i negocis que no poden estar caiguts.</p><p><a class="link-more" href="https://wa.me/34654225831?text=Hola%2C%20mi%20web%20-%20correo%20falla">Demanar ajuda web →</a></p>',
sv_a11: '<span class="tag">A MIDA</span><h3>11. Solució Software personalitzada</h3><p>Cap programa fa just lo que necessites? Creem menudes solucions a la teua mida: automatitzar tasques repetitives, documents que s’omplin sols, avisos automàtics, deixar de fer-ho tot a mà. Pressupost personalitzat després de diagnòstic i anàlisi de les teues necessitats, sense compromís.</p><p><a class="link-more" href="index.html#contacto">Demanar diagnòstic →</a> · <a class="link-more" href="https://wa.me/34654225831?text=Hola%2C%20quiero%20una%20soluci%C3%B3n%20de%20software%20a%20medida">Preguntar per WhatsApp →</a></p>',
sv_a12: '<span class="tag">TOT CONNECTAT</span><h3>12. Integració de servicis</h3><p>Correu per un costat, factures per un altre, còpies que ningú revisa, web desconnectada… Cada cosa solta et roba temps. Ho connectem tot perquè treballe junt: menys clics, menys errors, tot fluix. Pressupost personalitzat després de diagnòstic i anàlisi de les teues necessitats, sense compromís.</p><p><a class="link-more" href="index.html#contacto">Demanar diagnòstic →</a> · <a class="link-more" href="https://wa.me/34654225831?text=Hola%2C%20quiero%20integrar%20mis%20servicios">Preguntar per WhatsApp →</a></p>',
sv_e1: '<span class="tag">MATEIX DIA</span><h3>Urgències en el dia</h3><p>Si alguna cosa crítica falla, prioritat total. Tarifa clara per hora, sense marejos.</p><p><a class="link-more" href="https://wa.me/34654225831?text=Soy%20empresa%2C%20tengo%20urgencia%20hoy">Demanar urgència →</a></p>',
sv_e2: '<h3>Lloc nou llest el primer dia</h3><p>Ordinador, correu, programes, impressora i accessos configurats. El teu empleat produïx des del minut u.</p><p><a class="link-more" href="https://wa.me/34654225831?text=Quiero%20preparar%20un%20puesto%20nuevo">Demanar lloc →</a></p>',
sv_e3: '<h3>Dades a salvo (backups)</h3><p>Instal·lació + quota de supervisió mensual. Si passa alguna cosa, recuperem. Dormir tranquil també és rendibilitat.</p><p><a class="link-more" href="precios.html#empresas">Vore preu backups</a></p>',
sv_e4: '<h3>Departament IT extern (iguala)</h3><p>2h de suport al mes per lloc (remot o presencial) + prioritat mateix dia laborable. Hores extra a tarifa reduïda. Sense contractar personal.</p><p><a class="link-more" href="precios.html#empresas">Vore què és la iguala</a></p>',
sv_e5: '<h3>Assessorament integral + configuracions</h3><p>Què comprar, què renovar, quin software val la pena. Decisions amb criteri, no per impuls comercial.</p><p><a class="link-more" href="https://wa.me/34654225831?text=Soy%20empresa%2C%20quiero%20asesoramiento">Demanar assessoria →</a></p>',
sv_e6: '<h3>Web i correu empresa</h3><p>Caigudes, dominis, hosting, WordPress. El teu aparador sempre obert.</p><p><a class="link-more" href="https://wa.me/34654225831?text=Mi%20web%20de%20empresa%20falla">Demanar ajuda →</a></p>',
sv_e7: '<span class="tag">A MIDA</span><h3>Software a mida per al teu negoci</h3><p>Eixe procés que feu a mà, eixes dades que cal copiar d’un lloc a un altre… Ho automatitzem amb solucions a la vostra mida: menys hores perdudes, menys errors humans. Pressupost personalitzat després de diagnòstic i anàlisi de necessitats.</p><p><a class="link-more" href="index.html#contacto">Demanar diagnòstic →</a></p>',
sv_e8: '<span class="tag">TOT CONNECTAT</span><h3>Integració de servicis i sistemes</h3><p>Facturació, correu, còpies de seguretat, web, CRM… Si cada sistema va per lliure, el negoci perd ritme. Els integrem perquè la informació fluïsca sola entre ells. Pressupost personalitzat després de diagnòstic i anàlisi de necessitats.</p><p><a class="link-more" href="index.html#contacto">Demanar diagnòstic →</a></p>',
sv_band_h: 'Parlem del teu cas?',
sv_band_p: 'Tria el teu servici o conta’ns-ho lliurement. Contestem hui. Telefona al <a href="tel:+34654225831">654 225 831</a> o escriu a <a href="mailto:andreumatic@gmail.com">andreumatic@gmail.com</a>.',
sv_band_wa: 'WhatsApp directe',
sv_band_pre: 'Vore preus'
};
window.AM_X3 = {
pr_eb: 'Preus · clars i sense lletra menuda',
pr_t: 'Sabràs lo que pagues abans de començar.',
pr_lead: 'Sense lletra menuda. Trieu el teu servici en <a class="link-more" href="servicios.html">Servicis</a>, vens ací a vore el preu, i ens escrius per a tancar hora. Si ho necessites hui mateix: +15€ (segons disponibilitat).',
pr_part_t: 'Particulars',
pr_r1: 'Visita i diagnòstic a casa<small>Gratis si es realitza el treball</small>',
pr_r2: 'Optimització de PC<small>Neteja, rendiment i arranc més ràpid</small>',
pr_r3: 'Recuperació de dades<small>Segons fallo i estat del disc/dispositiu</small>',
pr_r4: 'Manteniment preventiu',
pr_r5: 'PC a mida<small>Pressupost, muntatge i instal·lació torre nova (components a banda)</small>',
pr_r6: 'Assistent de compres tecnològiques',
pr_r7: 'Mudança a equip nou<small>Programes, archius i configuració migrats</small>',
pr_r8: 'Suport en remot',
pr_r9: 'El Teu Tècnic de Capçalera<small>Dubtes dia a dia PC, mòbil o apps, sense presses</small>',
pr_r10: 'Revisió seguretat digital<small>Contrasenyes, còpies, phishing</small>',
pr_r11: 'Smart home bàsic<small>Router, càmeres, endolls intel·ligents</small>',
pr_r12: 'Web: resolució i canvis<small>Configuracions i/o modificacions web · Caiguda, hosting, domini, correu, WordPress</small>',
pr_call1: '<b>Mateix dia:</b> si ho necessites hui, +15€ sobre el servici (segons espai en agenda).',
pr_call2: '<b>Garantia 15 dies</b> en el treball realitzat. No cobrix fallos de programes de tercers ni mal ús posterior.',
pr_cta_part: 'Demanar servici particular →',
pr_emp_t: 'Empreses i autònoms',
pr_e1: 'Urgències en el dia<small>Depenent del tipus de falla i la seua possible resolució</small>',
pr_e3: 'El Teu Tècnic de Capçalera<small>Dubtes del dia a dia, PC, mòbil o apps, en remot o presencial</small>',
pr_e4: 'Visita i diagnòstic en empresa<small>Gratis si es realitza el treball</small>',
pr_e5: 'Lloc nou llest el primer dia',
pr_e6: 'Dades a salvo (backups)<small>Còpies de seguretat · instal·lació + supervisió</small>',
pr_e7: 'Departament IT extern (iguala)<small>Per lloc / mes</small>',
pr_e8: 'Assessorament integral',
pr_e9: 'Configuracions extra',
pr_e10: 'Web: resolució i canvis<small>Configuracions i/o modificacions web</small>',
pr_call3: '<b>Què és la iguala?</b> Per cada lloc: 2h de suport al mes (remot o presencial) + prioritat mateix dia laborable. Hores extra a 35€/h. No inclou backups ni hardware (a banda).',
pr_call4: '<b>Arreplegada i entrega a domicili</b> per a reparacions de taller — sense moure’t.',
pr_cta_emp: 'Demanar pressupost empresa →',
pr_not_t: 'Notes sobre preus',
pr_call5: '<b>🚗 Desplaçament des de 15€:</b> a València ciutat i rodalia (Paterna, Torrent, Mislata, Burjassot, Quart de Poblet, Aldaia, Manises, Paiporta, Alboraia, Xirivella i Alaquàs). Es confirma l’import exacte abans d’eixir. En remot no hi ha desplaçament (35€/h).',
pr_call6: '<b>Què significa “des de”?</b> És el preu mínim segons estat, núm. d’equips o abast. Sempre et donem <b>pressupost tancat abans</b> i només seguixes si t’encaixa.',
pr_call7: '<b>🛡️ Si no té arregle, no pagues de més:</b> només el diagnòstic. Et proposem l’alternativa més barata (recuperar dades, equip nou, etc.).',
pr_call8: '<b>** Tarifes no especificades:</b> pot haver-hi tarifes no especificades que es definiran segons la urgència, magnitud i resolució del problema.',
pr_notfoot: '*** Les tarifes poden patir canvis per demanda, disponibilitat, tipus de resolució o canvis de mercat.',
pr_band_h: 'Dubtes entre dos servicis?',
pr_band_back: '← Tornar a servicis',
};
window.AM_X4 = {
pr_e2: 'Suport en remot',
atc_lead: 'Parles amb qui ho arregla. Sense call centers ni 902.',
atc_h1: '1. Canals',
atc_p1: 'Telèfon i WhatsApp: <a class="link-more" href="tel:+34654225831">654 225 831</a> · Email: <a class="link-more" href="mailto:andreumatic@gmail.com">andreumatic@gmail.com</a>',
atc_h2: '2. Horari',
atc_p2: 'Dilluns a divendres, de 9:00 a 19:00. Fora d’horari pots escriure’ns i et responem al següent dia laborable.',
atc_h3: '3. Compromís de resposta',
atc_p3: 'Contestem el mateix dia laborable. Les urgències tenen prioritat amb el servici del mateix dia.',
atc_h4: '4. Zona de servici',
atc_p4: 'València i rodalia a domicili. Fora de zona? Gran part es resol en remot.',
av_lead: 'Qui som i baix quines regles funciona esta web.',
av_h1: '1. Dades del titular',
av_p1: 'Titular: Andreu Zaragozà i Arnàez · NIF: 48588243F<br>Domicili: Calle Mare Nostrum 6-4, 46930 Quart de Poblet (Valencia)<br>Contacte: <a class="link-more" href="tel:+34654225831">654 225 831</a> · <a class="link-more" href="mailto:andreumatic@gmail.com">andreumatic@gmail.com</a>',
av_h2: '2. Objecte de la web',
av_p2: 'Esta web informa dels nostres servicis i preus, i oferix canals de contacte. No permet contractar ni pagar online: tot servici es confirma directament amb el client per telèfon, email o WhatsApp.',
av_h3: '3. Preus',
av_p3: 'Els preus publicats són orientatius. El preu final es confirma amb el client abans de començar cada treball, després del diagnòstic. Cap extra s’aplica sense la seua aprovació prèvia. Vore <a class="link-more" href="precios.html#notas">notes sobre preus</a>.',
av_h4: '4. Propietat intel·lectual',
av_p4: 'Textos, imatges, logos i disseny d’esta web són titularitat d’AndreuMatic. No està permesa la seua reproducció sense autorització.',
av_h5: '5. Responsabilitat',
av_p5: 'Treballem perquè la informació estiga actualitzada, però no garantim la disponibilitat ininterrompuda de la web ni que estiga lliure d’errors. Els enllaços externs (p. ex. WhatsApp) es regixen per les condicions dels seus titulars.',
av_h6: '6. Llei aplicable',
av_p6: 'Legislació espanyola. Per a qualsevol conflicte seran competents els jutjats i tribunals de València, excepte norma imperativa en contra.',
pv_h1: 'Política de privacitat',
pv_lead: 'Clar i sense lletra menuda, com tot lo nostre.',
pv_r1: '1. Responsable',
pv_p1: 'Andreu Zaragozà i Arnàez (AndreuMatic) · NIF 48588243F · <a class="link-more" href="mailto:andreumatic@gmail.com">andreumatic@gmail.com</a> · <a class="link-more" href="tel:+34654225831">654 225 831</a>',
pv_r2: '2. Quines dades tractem',
pv_p2: 'Només les que tu ens facilites en contactar (formulari, email, telèfon o WhatsApp): nom, telèfon, email i la descripció del teu problema. Esta web no té comptes ni analítica. El formulari usa la verificació anti-spam Cloudflare Turnstile, que no utilitza cookies de seguiment.',
pv_r3: '3. Per a què i per què',
pv_p3: 'Per a respondre a les teues consultes i prestar-te el servici que contractes. Legitimació: el teu consentiment en escriure’ns i l’execució del servici (art. 6.1.a i 6.1.b del RGPD).',
pv_r4: '4. Quant de temps',
pv_p4: 'Només el necessari per a atendre’t i complir obligacions legals (p. ex. facturació). Després, s’eliminen.',
pv_r5: '5. Destinataris',
pv_p5: 'No cedim dades a tercers, excepte obligació legal. Si ens escrius per WhatsApp, tingues en compte que Meta processa eixos missatges segons la seua pròpia política de privacitat.',
pv_r6: '6. Els teus drets',
pv_p6: 'Accés, rectificació, supressió, oposició, limitació i portabilitat: escriu-nos a <a class="link-more" href="mailto:andreumatic@gmail.com">andreumatic@gmail.com</a> i ho resolem. També pots reclamar davant l’Agència Espanyola de Protecció de Dades (aepd.es).',
ac_h1: 'Declaració d’accessibilitat',
ac_lead: 'Esta web és per a tots. Si alguna cosa t’ho posa difícil, digue’ns-ho i ho arreglem.',
ac_r1: '1. Compromís',
ac_p1: 'AndreuMatic es compromet que esta web siga accessible conforme a la Llei 11/2023 de transposició de la Directiva (UE) 2019/882, amb l’objectiu de complir el nivell AA de les WCAG 2.1.',
ac_r2: '2. Mesures aplicades',
ac_p2: 'Textos alternatius en imatges, contrast reforçat, navegació completa per teclat, disseny responsive per a mòbil i llenguatge clar sense tecnicismes.',
ac_r3: '3. Limitacions',
ac_p3: 'Alguns continguts de tercers (p. ex. mapes o chats externs) poden no complir plenament estos criteris. Treballem a revisar-los i oferir alternatives.',
ac_r4: '4. Contacte davant barreres',
ac_p4: 'Si trobes alguna barrera d’accés, escriu-nos a <a class="link-more" href="mailto:andreumatic@gmail.com">andreumatic@gmail.com</a> o telefona al <a class="link-more" href="tel:+34654225831">654 225 831</a>. Responem en un màxim de 15 dies laborables.',
ac_rev: 'Última revisió: setembre de 2026.',
en_lead: 'Ací no hi ha enviaments: hi ha servici a domicili, remot i arreplegada. Açò és lo que pots esperar.',
en_h1: '1. Com es presta el servici',
en_p1: 'A domicili a València i rodalia, en remot, o amb arreplegada i entrega del teu equip en taller. No realitzem enviaments de productes: el nostre treball és el servici tècnic.',
en_h2: '2. Terminis',
en_p2: 'Els terminis són orientatius i es confirmen en contractar cada servici. Les urgències s’atenen el mateix dia laborable segons disponibilitat.',
en_h3: '3. Garantia',
en_p3: '15 dies en el treball realitzat. No cobrix fallos de programes de tercers ni mal ús posterior.',
en_h4: '4. Com reclamar',
en_p4: 'Telefona’ns al <a class="link-more" href="tel:+34654225831">654 225 831</a>, escriu-nos a <a class="link-more" href="mailto:andreumatic@gmail.com">andreumatic@gmail.com</a> o per <a class="link-more" href="https://wa.me/34654225831?text=Hola%20AndreuMatic%2C%20quiero%20poner%20una%20reclamación">WhatsApp</a>. També tens a la teua disposició els fulls de reclamacions de la Generalitat Valenciana i la plataforma europea de resolució de litigis en línia: <a class="link-more" href="https://ec.europa.eu/consumers/odr">ec.europa.eu/consumers/odr</a>.',
fof_h1: 'Vaja, açò s’ha trencat… però jo ho arregle.',
fof_p: 'La pàgina no existix. Millor parlem directament.'
};
window.AM_X5 = {
pg_cita_t: 'Demanar cita | AndreuMatic',
pg_cita_d: 'Reserva la teua cita amb AndreuMatic a València: tria dia i hora, rep confirmació. Diagnòstic des de 25€.',
ci_crumb: 'Demanar cita',
ci_eb: 'Reserva el teu espai',
ci_t: 'Agenda la teua cita en 1 minut',
ci_lead: 'Tria dia i hora dels espais disponibles reals. Rep confirmació al moment i t’avisem abans. Sense registres ni apps.',
ci_s1t: '1. Tria dia i hora',
ci_s1p: 'Calendari amb disponibilitat real, actualitzat al moment.',
ci_s2t: '2. Deixa les teues dades',
ci_s2p: 'Nom, telèfon i què et passa. Només lo necessari.',
ci_s3t: '3. Et confirmem',
ci_s3p: 'Confirmació immediata + recordatori per WhatsApp o email.',
ci_alt: 'Prefirixes escriure? <a class="link-more" href="index.html#contacto">Ves al formulari →</a> o <a class="link-more" href="https://wa.me/34654225831?text=Hola%20AndreuMatic%2C%20quiero%20pedir%20cita">WhatsApp directe</a>.'
};
window.AM_X6 = {
sl_t: 'Disponibilitat esta setmana'
};
